apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-ui
  namespace: ai-client
---
apiVersion: v1
kind: Service
metadata:
  name: curl-ui
  namespace: ai-client
  labels:
    app: curl-ui
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: curl-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-ui-deployment
  namespace: ai-client
  labels:
    app: curl-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-ui
  template:
    metadata:
      labels:
        app: curl-ui
    spec:
      serviceAccountName: curl-ui
      containers:
      - name: curl-ui
        image: ably77/curl-ui:0.5.4
        ports:
        - containerPort: 5000
        env:
          - name: CURL_UI_TITLE
            value: "Simple Curl UI"
          #- name: REQUEST_URL_PLACEHOLDER
          #  value: "https://ai-gateway.demo.glooplatform.com/openai"
          - name: DEFAULT_HTTP_METHOD
            value: "GET"
