# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- openai-ns.yaml
- ai-client-ns.yaml
#- chatgpt-client.yaml
- curl-ui.yaml
- ai-client-demos

# patch nodeSelector and tolerations on all Deployments
patches:
- patch: |-
    kind: not-important
    metadata:
      name: not-important
    spec:
      template:
        spec:
          nodeSelector:
            gke-spot: "true"
          tolerations:
          - key: cloud.google.com/gke-spot
            operator: Equal
            value: "true"
            effect: NoSchedule
  target:
    kind: Deployment