apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: TransformationPolicy
metadata:
  name: anthropic-eli5-prompt-transformation
  namespace: ai-gateway-ws-config
spec:
  applyToRoutes:
  - route:
      labels:
        prompt-template: "claude-eli5"
  config:
    request:
      injaTemplate:
        # set default header for version
        headers:
          anthropic-version:
            text: '2023-06-01'
        # input prompt template
        body:
          text: |
            {
                "model": "claude-3-opus-20240229",
                "max_tokens": 1024,
                "temperature": {{ temp }},
                "system": "What would you like me to explain like I am 5 years old?",
                "messages": [
                    {"role": "user", "content": "{{ ask_here }}"}
                ]
            }
    #response:
    #  injaTemplate:
    #    body:
    #      text: | 
    #        {{ content }}
