apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: anthropic-eli5-rt
  namespace: ai-gateway-ws-config
  labels:
    llm-type: anthropic
    prompt-template: "claude-eli5"
spec:
  http:
    - name: eli5-translator
      matchers:
      - uri:
          prefix: /claude
        headers:
        - name: x-template
          value: "eli5"
      forwardTo:
        pathRewrite: /v1/messages
        hostRewrite: api.anthropic.com
        destinations:
        - kind: EXTERNAL_SERVICE
          port:
            number: 443
          ref:
            name: anthropic-externalservice
            namespace: ai-gateway-ws-config