apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: anthropic-catchall-rt
  namespace: ai-gateway-ws-config
  labels:
    llm-type: anthropic
    prompt-template: "none"
spec:
  http:
    - name: catch-all
      matchers:
      - uri:
          prefix: /claude
      - uri:
          prefix: /v1/messages
      forwardTo:
        pathRewrite: /v1/messages
        hostRewrite: api.anthropic.com
        destinations:
        - kind: EXTERNAL_SERVICE
          port:
            number: 443
          ref:
            name: anthropic-externalservice
            namespace: ai-gateway-ws-config