apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: podinfo-vd1
  namespace: podinfo-team-config
  labels:
    failover: "true"
spec:
  hosts:
  - podinfo.randomvalue1
  services:
  - namespace: podinfo
    labels:
      app: podinfo
    cluster: gke-east
  - namespace: podinfo
    labels:
      app: podinfo
    cluster: gke-central
  ports:
    - number: 9898
      protocol: HTTP