#Route table can reside in just primary cluster, we dont need now in DR cluster
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin-delegate-rt
  namespace: httpbin-blue
spec:
  http:
    - name: httpbin
      matchers:
      - uri:
          exact: /get
      - uri:
          prefix: /callback
      - uri:
          prefix: /logout
      - uri:
          prefix: /anything
      forwardTo:
        destinations:
        - ref:
            #name: httpbin-blue-vd
            #namespace: httpbin-blue
            labels:
              vd: httpbin-blue
          kind: VIRTUAL_DESTINATION
          port:
            number: 8000
          weight: 50
        - ref:
            labels:
              vd: httpbin-green
            #name: httpbin-green-vd
            #namespace: httpbin-blue
          kind: VIRTUAL_DESTINATION
          port:
            number: 8000
          weight: 50