apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-blue
  namespace: httpbin-blue
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-blue
  namespace: httpbin-blue
  labels:
    app: httpbin-blue
    service: httpbin-blue
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin-blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-blue
  namespace: httpbin-blue
  labels:
    app: httpbin-blue
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-blue
      version: v1
  template:
    metadata:
      labels:
        app: httpbin-blue
        version: v1
        istio.io/rev: 1-22
    spec:
      serviceAccountName: httpbin-blue
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin-blue
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-blue-canary
  namespace: httpbin-blue
  labels:
    app: httpbin-blue
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-blue
      version: v2
  template:
    metadata:
      labels:
        app: httpbin-blue
        version: v2
        istio.io/rev: 1-22
    spec:
      serviceAccountName: httpbin-blue
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin-blue
        ports:
        - containerPort: 80