apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin-rt-443
  namespace: httpbin-team-config
  labels:
    expose: "true"
spec:
  hosts:
    - '*'
  virtualGateways:
  - cluster: mgmt
    name: cluster1-north-south-gw-443
    namespace: istio-gateways
  - cluster: mgmt
    name: cluster2-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []
  http:
    - delegate:
        routeTables:
          - namespace: httpbin-blue
      labels:
        ingress: all
      name: httpbin-delegate