apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: httpbin-vd
  namespace: httpbin-team-config
  labels:
    failover: "true"
spec:
  hosts:
  - httpbin.randomvalue
  services:
  - labels:
      app: httpbin-blue
  - labels:
      app: httpbin-green
  ports:
    - number: 8000
      protocol: HTTP