{
 "title": "Gloo Platform Operations",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "GlooPrometheus", "label": "Gloo Prometheus", "query": "prometheus" },
   { "name": "ExternalPrometheus", "label": "External Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Gloo Management Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Translation Times Histogram",
   "type": "heatmap",
   "description": "Count of translations times that were in a given time in seconds",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gloo_mesh_translation_time_sec_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Recon Times Histogram",
   "type": "heatmap",
   "description": "Count of translations times that were in a given time in seconds",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gloo_mesh_reconciler_time_sec_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Translation Warnings",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(translation_warning) by (pod,namespace,workspace,gvk)"
    }
   ]
  },
  {
   "title": "Translation Errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(translation_error) by (pod,namespace,workspace,gvk)"
    }
   ]
  },
  {
   "title": "Translation Time Percentiles",
   "type": "timeseries",
   "description": "Count of translations times that were in a given time in seconds",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gloo_mesh_translation_time_sec_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gloo_mesh_translation_time_sec_bucket[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(gloo_mesh_translation_time_sec_bucket[5m])) by (le))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "Recon Time Percentiles",
   "type": "timeseries",
   "description": "Count of translations times that were in a given time in seconds",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gloo_mesh_reconciler_time_sec_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gloo_mesh_reconciler_time_sec_bucket[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(gloo_mesh_reconciler_time_sec_bucket[5m])) by (le))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "Gloo Translator Concurrency",
   "type": "stat",
   "description": "Number of translators that can run concurrently",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gloo_mesh_translator_concurrency) by (pod)"
    }
   ]
  },
  {
   "title": "Redis Sync Errors (last 10m)",
   "type": "stat",
   "description": "Number of errors when trying to sync with Redis",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(gloo_mesh_redis_sync_err{app=\"gloo-system-mgmt-server\"}[10m]))"
    }
   ]
  },
  {
   "title": "Gloo Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Agents Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{app=\"gloo-system-mgmt-server\"}) / count(relay_pull_clients_connected{app=\"gloo-system-mgmt-server\"})"
    }
   ]
  },
  {
   "title": "Total Agent Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected)"
    }
   ]
  },
  {
   "title": "Agent Clusters Not Warmed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(relay_push_clients_warmed == 0) by(cluster))"
    }
   ]
  },
  {
   "title": "Agents Connected To each Management Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{app=\"gloo-system-mgmt-server\"})by (pod)"
    }
   ]
  },
  {
   "title": "Agents Connected To Each Mgmt Pod",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(relay_pull_clients_connected{app=\"gloo-system-mgmt-server\"}) by (pod,cluster)"
    }
   ]
  },
  {
   "title": "Gloo Telemetry Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receivers: Metric Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points[5m])) by (receiver)",
     "legendFormat": "Accepted rate: {{receiver}}"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points[5m])) by (receiver)",
     "legendFormat": "Refused rate: {{receiver}}"
    }
   ]
  },
  {
   "title": "Processors: Batch metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_count[5m])) by (processor)",
     "legendFormat": "Batch send size count: {{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum[5m])) by (processor)",
     "legendFormat": "Batch send size sum: {{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_batch_timeout_trigger_send[5m])) by (processor)",
     "legendFormat": "Batch timeout rate: {{processor}}"
    }
   ]
  },
  {
   "title": "Exporters: Metric Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points[5m])) by (exporter)",
     "legendFormat": "Sent metric points: {{exporter}}"
    },
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_metric_points[5m])) by (exporter)",
     "legendFormat": "Enqueue failed metric points rate: {{exporter}}"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points[5m]))",
     "legendFormat": "Sent failed rate: {{exporter}}"
    }
   ]
  },
  {
   "title": "Gloo Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Gloo vCPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"gloo-system\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"gloo-system\", type=\"hard\",resource=\"requests.cpu\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"gloo-system\", type=\"hard\",resource=\"limits.cpu\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "Gloo Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"gloo-system\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"gloo-system\", type=\"hard\",resource=\"requests.memory\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "scalar(kube_resourcequota{namespace=\"gloo-system\", type=\"hard\",resource=\"limits.memory\"})",
       "legendFormat": "quota - limits"
      }
     ]
    }
   ]
  }
 ]
}