apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: language-chatbot-route-policies
  namespace: ai-chatbot
spec:
  options:
    extauth:
      configRef:
        name: language-chatbot-okta
        namespace: gloo-system