apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: language-chatbot-route-policies
  namespace: ai-chatbot
spec:
  options:
    # jwt validation is enabled when using this policy
    jwt:
      disable: false
    # validated claim must include org: internal
    rbac:
      policies:
        viewer:
          nestedClaimDelimiter: .
          principals:
          - jwtPrincipal:
              claims:
                org: internal
                
    