
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: bedrock-route-policies
  namespace: gloo-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: bedrock-route
  options:
    jwt:
      disable: true
    timeout: "0"
    hostRewrite: 'bedrock-runtime.us-west-2.amazon.aws.com'
---