apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin-rt-443
  namespace: httpbin-config
  labels:
    expose: "true"
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: httpbin
      labels:
        httpbin-oauth: "true"
        waf: "true"
        ratelimited: "true"
      matchers:
      - uri:
          prefix: /
      - uri:
          exact: /get
      - uri:
          prefix: /callback
      - uri:
          prefix: /logout
      - uri:
          prefix: /anything
      forwardTo:
        destinations:
        - ref:
            name: httpbin-blue
            namespace: httpbin-blue
          port:
            number: 8000
          weight: 50
        - ref:
            name: httpbin-green
            namespace: httpbin-green
          port:
            number: 8000
          weight: 50