{
 "title": "API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api_id",
    "label": "Api ID",
    "query": "Select DISTINCT (LogAttributes['api_id'])\nFROM\n  gloo_api_logs\nWHERE\n  LogAttributes['api_id'] IS NOT NULL AND\n  LogAttributes['api_id'] != '' AND\n  LogAttributes['api_id'] != '<nil>'"
   },
   {
    "name": "usage_plan",
    "label": "Usage Plan",
    "query": "Select DISTINCT(LogAttributes['usage_plan'])\nFROM\n  gloo_api_logs\nWHERE\n  LogAttributes['usage_plan'] IS NOT NULL AND\n  LogAttributes['usage_plan'] != '' AND\n  LogAttributes['usage_plan'] != '<nil>'"
   },
   {
    "name": "request_uri",
    "label": "Request URI",
    "query": "select distinct(LogAttributes['request_uri']) requestUri from gloo_api_logs"
   },
   {
    "name": "http_method",
    "label": "HTTP Method",
    "query": "select distinct(LogAttributes['request_command']) as requestCommand from gloo_api_logs"
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": "select distinct(LogAttributes['status_code']) as statusCode from gloo_api_logs"
   },
   {
    "name": "user_id",
    "label": "User ID",
    "query": "select distinct(LogAttributes['user_id']) as userId from gloo_api_logs\nwhere userId like '$filter_users%' AND userId != '<nil>'\nLIMIT 100"
   },
   { "name": "filter_users", "label": "Filter Users" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests in this period",
   "type": "stat",
   "description": "Total requests to all of your APIs",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nORDER BY\n  count Desc\nlimit\n  20\n"
    }
   ]
  },
  {
   "title": "Total active users",
   "type": "stat",
   "description": "Total active users in this period",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT(LogAttributes['user_id']) as userId) as userCount\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri)\nlimit\n  20\n"
    }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  LogAttributes['bytes_sent'] as bytes_sent,\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n bytes_sent\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  LogAttributes['bytes_received'] as bytes_received,\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n bytes_received\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Server error count",
   "type": "stat",
   "description": "Server error count in this period (5xx status codes)",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  CAST(LogAttributes['status_code'] AS INT) >= 500 AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nORDER BY\n  count Desc\nlimit\n  20\n"
    }
   ]
  },
  {
   "title": "User error count",
   "type": "stat",
   "description": "User error count in this period (4xx status codes)",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  CAST(LogAttributes['status_code'] AS INT) >= 400 AND CAST(LogAttributes['status_code'] AS INT) < 500 AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nORDER BY\n  count Desc\nlimit\n  20\n"
    }
   ]
  },
  {
   "title": "Status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeInterval(Timestamp) AS time,\n  LogAttributes['status_code'] AS statusCode,\n  count(*) as count\nFROM \n  gloo_api_logs\nWHERE \n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n  statusCode, \n  time\nORDER BY \n  time ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "API Product distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeInterval(Timestamp) AS time,\n  LogAttributes['api_id'] AS apiId,\n  count(*) AS count\nFROM \n  gloo_api_logs\nWHERE \n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n  apiId, \n  time\nORDER BY \n  time ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \n*\nFROM \n  gloo_api_logs\nWHERE \n  $__timeFilter(Timestamp)",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Bytes sent over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LogAttributes['bytes_sent'] as bytes_sent,\n  $__timeInterval(Timestamp) AS time,\n  count(*) AS bytes\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n bytes_sent,\n time\nORDER BY \n  time ASC\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.25)(CAST(LogAttributes['response_duration'] AS INT)) as p25\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time\n\n",
     "selectedFormat": 1
    },
    {
     "rawSql": "\nSELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.5)(CAST(LogAttributes['response_duration'] AS INT)) as p50\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.75)(CAST(LogAttributes['response_duration'] AS INT)) as p75\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.90)(CAST(LogAttributes['response_duration'] AS INT)) as p90\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.95)(CAST(LogAttributes['response_duration'] AS INT)) as p95\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.99)(CAST(LogAttributes['response_duration'] AS INT)) as p99\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.999)(CAST(LogAttributes['response_duration'] AS INT)) as p999\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp)\nGROUP BY time\nORDER BY time",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Top API consumers",
   "type": "table",
   "description": "Usage for API '$api_id' with usage plan '$usage_plan'",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(LogAttributes['user_id'] AS VARCHAR) as User,\n  count(*) AS Count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY\n  User\nORDER BY\n  Count Desc"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(LogAttributes['user_agent'] AS VARCHAR) as user_agent,\n  count(*) AS Count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY\n  user_agent\nORDER BY\n  Count Desc",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "API '$api_id' Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "api_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests",
     "type": "stat",
     "description": "Total requests in this period for the API '$api_id'",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  LogAttributes['api_id'] as apiId,\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY\n  apiId\nORDER BY\n  count Desc\nlimit\n  20\n"
      }
     ]
    },
    {
     "title": "Total active users",
     "type": "stat",
     "description": "Total active users in this period",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(DISTINCT(LogAttributes['user_id']) as userId) as userCount\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri)\nlimit\n  20\n"
      }
     ]
    },
    {
     "title": "Server error count",
     "type": "stat",
     "description": "Server error count in this period (5xx status codes)",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  CAST(LogAttributes['status_code'] AS INT) >= 500 AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nORDER BY\n  count Desc\nlimit\n  20\n"
      }
     ]
    },
    {
     "title": "User error count",
     "type": "stat",
     "description": "User error count in this period (4xx status codes)",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(*) AS count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  CAST(LogAttributes['status_code'] AS INT) >= 400 AND CAST(LogAttributes['status_code'] AS INT) < 500 AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nORDER BY\n  count Desc\nlimit\n  20\n"
      }
     ]
    },
    {
     "title": "Top API consumers",
     "type": "table",
     "description": "Usage for API '$api_id' with usage plan '$usage_plan'",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  CAST(LogAttributes['user_id'] AS VARCHAR) as User,\n  count(*) AS Count\nFROM\n  gloo_api_logs\nWHERE\n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY\n  User\nORDER BY\n  Count Desc"
      }
     ]
    },
    {
     "title": "Requests over time",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 7, "x": 7, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeInterval(Timestamp) AS time,\n  LogAttributes['api_id'] AS apiId,\n  count(*) AS count\nFROM \n  gloo_api_logs\nWHERE \n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n  apiId, \n  time\nORDER BY \n  time ASC"
      }
     ]
    },
    {
     "title": "Status codes over time",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeInterval(Timestamp) AS time,\n  LogAttributes['status_code'] AS statusCode,\n  count(*) as count\nFROM \n  gloo_api_logs\nWHERE \n  $__timeFilter(Timestamp) AND\n  LogAttributes['api_id'] IN ($api_id) AND\n  LogAttributes['usage_plan'] IN ($usage_plan) AND\n  LogAttributes['status_code'] IN ($status_code) AND\n  LogAttributes['request_command'] IN ($http_method) AND\n  LogAttributes['request_uri'] IN ($request_uri) AND\n  ('$user_id' = 'All' OR LogAttributes['user_id'] = '$user_id')\nGROUP BY \n  statusCode, \n  time\nORDER BY \n  time ASC"
      }
     ]
    },
    {
     "title": "Request latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 7, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.25)(CAST(LogAttributes['response_duration'] AS INT)) as p25\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time\n\n",
       "selectedFormat": 1
      },
      {
       "rawSql": "\nSELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.5)(CAST(LogAttributes['response_duration'] AS INT)) as p50\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.75)(CAST(LogAttributes['response_duration'] AS INT)) as p75\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.90)(CAST(LogAttributes['response_duration'] AS INT)) as p90\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.95)(CAST(LogAttributes['response_duration'] AS INT)) as p95\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.99)(CAST(LogAttributes['response_duration'] AS INT)) as p99\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time"
      },
      {
       "rawSql": "SELECT\n    $__timeInterval(Timestamp) AS time,\n    quantileExact(0.999)(CAST(LogAttributes['response_duration'] AS INT)) as p999\nFROM\n    gloo_api_logs\nWHERE\n    $__timeFilter(Timestamp) AND\n    LogAttributes['api_id'] IN ($api_id)\nGROUP BY time\nORDER BY time"
      }
     ]
    }
   ]
  }
 ]
}