apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: argocd
spec:
  hosts:
  - "argocd.west.gmc.glooplatform.com"
  gateways:
  - istio-system/http-gateway
  http:
  - name: argo-ui
    match:
    - uri:
        prefix: /argo
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server
        port:
          number: 443