apiVersion: v1
kind: Secret
metadata:
  name: okta-client-secret
  namespace: gloo-system
type: extauth.solo.io/oauth
data:
  client-secret: ekVhNllGQ1NYeGQ5b2t6cHJhTkMtNlNYQThLZzFJREdzMmZhcEtZSjNqakpNUGpQNTYzZ1QzLWZSakNLbC1hYw==