apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: oidc-auth
  namespace: external-portal-config
spec:
  applyToRoutes:
    - route:
        labels:
          auth: oidc
  config:
    server:
      name: mgmt-ext-auth-server
      namespace: gloo-mesh
      cluster: mgmt
    glooAuth:
      configs:
        - oauth2:
            accessTokenValidation:
              jwt:
                # remoteJwks:
                #   url: "https://dev-29199769.okta.com/oauth2/default/v1/keys"
                #   refreshInterval: 5m
                localJwks:
                #  # found here: https://dev-<USER>.okta.com/oauth2/default/v1/keys
                 inlineString: >-
                     {"keys":[{"kty":"RSA","alg":"RS256","kid":"AOwp96lRFLTJmGabIqHqZrzf8vWNex1aCCCmqN9G1jM","use":"sig","e":"AQAB","n":"yfYB7_S9Jx78QxqKeYulmZuoDBQtYNSE_tknMVMTOPYtk18AdMuP7ejPFCY9TmerCXCcoRIRthIFrgcNdvJAR0r7F8D6LQw-BlEZXiZuxb-coTgKv0Cqi1s8_QPN4_1mXDURHGozfwWjZXTdi49L8cAt0c8T3kF__o0DcpmvltSSED_OGNZNXVnv6Oa2QA2qm7Rg1ft-VvWrnQz9qWq5tvTnQ1migWn0KeFOsucTQmMNczHYrijTqFN2Mg1Ya3tGXP7bFRBWiEc_Yja6fBkerX_Zek4t0p_uNmm-gU0nKjIOK7_c79nY9nNnmPRMjeJagdCzkfotNLFYop7tul-78Q"}]}